### ISSUE TITLE
Add model specific column to seurat metadata using different models

### ISSUE THREAD

**Issue by GWMcElfresh** [bimberlabinternal/RIRA#52]
@bbimber, does anything break if we change 
https://github.com/bimberlabinternal/RIRA/blob/8151dd169e797e086b3b668f50ca287e9ea6c5ed/R/CellTypist.R#L106

to 

`seuratObj <- Seurat::AddMetaData(seuratObj, labels, col.name = gsub(".pkl", "", modelName))`? 

or we could leverage columnPrefix?

**Comment by GWMcElfresh** [comment]
perhaps also suffixed with _cellTypist or something in case we want to do a consensus caller like we did with singleR

**Comment by bbimber** [comment]
Like we talked about on teams, RunCellTypist already has a columnPrefix argument. I'll add support for that on prime-seq
