### ISSUE TITLE
Downloading every time cellTypist is run

### ISSUE THREAD

**Issue by KerryAM-R** [bimberlabinternal/RIRA#72]
I'm wondering if there is a parameter to prevent the RunCellTypist from downloading the models everytime?

Cheers,
Kerry

**Comment by bbimber** [comment]
@KerryAM-R: thanks for the feedback. we usually run this headlessly on our cluster so I dont notice that. I added an argument for runCelltypistUpdate, which you can set to FALSE: https://github.com/bimberlabinternal/RIRA/blob/b318ac0578862b1280de7f714dc4aaa579b23cdf/R/CellTypist.R#L26
